name: Hexo Blog CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd ./public && touch .nojekyll && git init && git config --global --add safe.directory /github/workspace && git config user.name "github-actions[bot]" && git config user.email "github-actions[bot]@users.noreply.github.com" && git add . && git commit -m "Deploy $(date -u +'%Y-%m-%d %H:%M:%S')" && git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/wfh168/wfh168.github.io.git" HEAD:gh-pages